
import Header from '@/components/header/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/Footer'
import { Provider } from 'react-redux'
import { store } from '@/features/store'
import ReduxProvider from '@/features/provider'
import CategoryRoutes from '@/features/slices/categoryRotes'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <CategoryRoutes />
          <Header />
          {children}
          <Footer/>
        </ReduxProvider>
      </body>
    </html>
  )
}
